# Generated by Django 3.0.5 on 2020-09-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='textlang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('lang', models.CharField(choices=[('Spanish', 'en-es'), ('English', 'es-en')], max_length=15)),
            ],
        ),
    ]
